#!/usr/bin/python

import shutil

FRAMES = [0, 0, 0, 4, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 3, 0, 1]

seq = 0
for f in FRAMES:
    shutil.copyfile("out/frame-%d.gif" % f,
                    "out/sframe-%00d.gif" % seq)
    seq += 1
